title: Bilal Balcı # your name (or website title) here
logo: "/images/CV_Resim.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A Civil Engineer with Masters' Degree 
  <br>Indie Game Developer<br>
  1 Year Experience on GameDev 
  <br>Trying to find a position in GameDev Community<br>
  
  <br> <a href="https://bilalbalci.weebly.com">View My Web Page</a> <br>
  
  <a href="https://www.linkedin.com/in/bilal-balci-66577495/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-148881176-1 # your Google Analytics tracking ID here
