title: Bilal Balcı # your name (or website title) here
logo: "/images/CVResim.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Game Developer<br>
  Second description 
  <br>Portfolio<br>
  <a href="https://www.linkedin.com/in/bilal-balci-66577495/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-148881176-1 # your Google Analytics tracking ID here
